# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 509035e7f5df25155168d3fe2ad8b5d791f5bb105da16968eaa759d5405f34d009bbda0e0b64849770ca3755a21f66e112446882363c7d92a63157b8ba50615a

test:
  secret_key_base: 724eac99c317bf0cef336cea994ada94aa656f935aab63440899db87901b3dbda7d67e34ff8d8d3c0db1b10e6fc76130dc6543ee23c4b837bf12961509873111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
